version: '3.8'

services:
  backend:
    build:
      context: ./Backend/FlightSearch
      dockerfile: Dockerfile
    ports:
      - "5175:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_HOST=${REDIS_HOST}
      - AMADEUS_API_KEY=${AMADEUS_API_KEY}
      - AMADEUS_API_SECRET=${AMADEUS_API_SECRET}
    depends_on:
      - redis
    restart: on-failure

  frontend:
    build:
      context: ./Frontend/flight-search-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"  
    depends_on:
      - backend

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
